### ISSUE TITLE
TabBar

### ISSUE THREAD

**Issue by romaluca** [fluttercommunity/flutter_sticky_headers#2]
Hi doesn't work with tabbar

**Comment by j4k0bk** [comment]
Could you post an example?

**Comment by alantbarlow** [comment]
I can not get it to work properly with a tab bar either. since you requested an example, the code is listed below. the problem is, when you switch tabs and switch back, the list forgets what header should be attached to the top so it doesn't display one and it shows the incorrect header below it. once you initiate a scroll it will instantly start working again, show the proper headers as well as the right header attached to the top.




`class ContactsPage extends StatelessWidget {
  final TabController _controller;
  ContactsPage(Key key, this._controller) : super(key: key);

  final List _allList = List.generate(10, (index) => "Contact $index");
  
  final List<Widget> _tabs = [
    Tab(text: "All"),
    Tab(text: "Recent"),
    Tab(text: "Groups"),
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        TabbedAppBar(
          title: "Contacts",
          controller: _controller,
          tabs: _tabs,
        ),
        Expanded(
          child: TabBarView(
            key: PageStorageKey("ContactsTabBarView"),
            controller: _controller,
            children: <Widget>[
              ListView.builder(
                key: PageStorageKey("AllScrollPosition"),
                controller: ScrollController(),
                itemCount: 200,
                itemBuilder: (buildContext, index) => StickyHeader(
                      key: PageStorageKey("AllListHeader"),
                      header: Container(
                        color: Theme.of(context).primaryColor,
                        height: 50,
                        padding: EdgeInsets.symmetric(horizontal: 16.0),
                        alignment: Alignment.centerLeft,
                        child: Text("Header $index"),
                      ),
                      content: Column(
                        children: _allList
                            .map(
                              (value) => ListTile(
                                    title: Text(value),
                                  ),
                            )
                            .toList(),
                      ),
                    ),
              ),
              ListView.builder(
                key: PageStorageKey("RecentScrollPosition"),
                controller: ScrollController(),
                itemCount: 500,
                itemExtent: 60.0,
                itemBuilder: (buildContext, index) {
                  return Center(
                    child: Text("B: $index"),
                  );
                },
              ),
              ListView.builder(
                key: PageStorageKey("GroupsScrollPosition"),
                controller: ScrollController(),
                itemCount: 500,
                itemExtent: 60.0,
                itemBuilder: (buildContext, index) {
                  return Center(
                    child: Text("C: $index"),
                  );
                },
              ),
            ],
          ),
        ),
      ],
    );
  }
}
`

**Comment by bgetsug** [comment]
https://github.com/letsar/flutter_sticky_header is working better for me within `TabBarView`

**Comment by hs029** [comment]
I tried https://github.com/letsar/flutter_sticky_header, put it in tabview, it doesn't work. Same behavior as  AlanTBarlow's case.
